### ISSUE TITLE
Linux applying theme doesn'y change the appreance of Spotify

### ISSUE THREAD

**Issue by AndreiIonica** [khanhas/spicetify-cli#1085]
## ℹ Computer information

- Spotify version: 1.1.68
- Spicetify version: 2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. Install themes from [here](https://github.com/morpheusthewhite/spicetify-themes)
2. ```spicetify config current_theme Cherry```
3. ```spicetify apply```

### ✔️ Expected result
It works

_What is the expected result of the above steps?_

### ❌ Actual result

It doesn't work.Commands runs without error but theme isn't applied.
_What is the actual result of the above steps?_

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/40264929/134761211-7f23afcc-988e-498b-a829-085aff364b92.png)

_Are there any useful screenshots?_

## Additional
I am running Linux Mint 20.2.Spotify was installed through apt.It was working on last version.
When I ran apt upgrade Spotify went back to default theme.I tried applying the theme again and it didn't work.

Stuff I have tried:
- 

- ~chown~ chmod 777 /usr/share/spotify/Apps.It still errors.Also when I run ls the folder is empty.

- Reinstall Spotify and spicetify-cli
- Restart PC

**Comment by TheGeeKing** [comment]
> chown 777

Shouldn't be chmod and not chown??

* chown defines who owns the file.
* chmod defines who can do what.

You should try `chmod 777`

**Comment by AndreiIonica** [comment]
You are right.I meant to type chmod and wrote chown instead.

**Comment by AndreiIonica** [comment]
Maybe relevant to the issue: when Spotify is first installed that folder isn't empty.After runninf ```spicetify apply``` it becomes empty.

**Comment by AndreiIonica** [comment]
More additional info: if i try to chmod the whole folder(```/usr/share/spotify/```,not just the Apps folder) it doesn't error out anymore.But the appearance of spotify doesn't change.

**Comment by TheGeeKing** [comment]
Hi @AndreiIonica,

You might want to take a look at issue #1032 and wiki documentation about linux: https://github.com/khanhas/spicetify-cli/wiki/Installation#linux-and-macos. If it still doesn't work let us know and please rename your issue like "Linux permission error applying theme" so people can more easily help you.

**Comment by AndreiIonica** [comment]
@TheGeeKing 
I will update the issue and title.Running ```chmod -R 777 /usr/share/spotify``` fixes all the errors.When I run ```spicetify apply`` it runs without error.However the appearance of Spotify doesn't change.

**Comment by TheGeeKing** [comment]
You need to do `spicetify enable-devtool` may need to apply after.

**Comment by AndreiIonica** [comment]
Here is a screnshot 

![image](https://user-images.githubusercontent.com/40264929/134761169-be37ada5-9a91-4df2-8e44-8dcb0817760a.png)

And here is text output:
```
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1033900
(anonymous) @ vendor~xpui.js:1
vendor~xpui.js:1 Uncaught TypeError: Spicetify.Player.origin2.state.addProgressListener is not a function
    at waitOrigins (spicetifyWrapper.js:182)
    at r (vendor~xpui.js:1)
xpui.js:1 Uncaught (in promise) Error: GET request to sp://ads/v1/settings/leaderboard failed with status code 404
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
vendor~xpui.js:1 Array(6)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/leaderboard
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubAdsService.setRequestNonPersonalizedAds("0"). Valid values: 0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
pubads_impl_2021092001.js?31062913:11 [GPT] Invalid argument: PubadsService.setTagForUnderAgeOfConsent("0"). Valid values: 2,0,1.
(anonymous) @ pubads_impl_2021092001.js?31062913:11
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/754.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-search.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by TheGeeKing** [comment]
Which Version of spicetify do you have? If you still have 2.6.4 update to 2.6.6 this has been fixed normally.

**Comment by AndreiIonica** [comment]
This fixed it.Will close issue.
