### ISSUE TITLE
Error Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by dfrazao** [khanhas/spicetify-cli#1094]
## ℹ Computer information

- Spotify version: 1.1.68.632.g2b11de83-a
- Spicetify version: 2.6.6

### ✔️ Expected result

When using the command "spicetify apply" the styles and custom apps should be applied.

### ❌ Actual result

When using the command "spicetify apply" an error occurs, while applying additional modifications, saying:
"error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0"

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/26813660/134676438-ccdfcff6-e0e0-43e9-a6f8-4b458139d5a6.png)

**Comment by afonsojramos** [comment]
Please do a fresh install of Spicetify by first removing the `.spicetify` and `spicetify-cli` folders.
Let me know the result.

**Comment by jack-mil** [comment]
I am also experiencing this issue on the same versions as @dfrazao on Windows 10. I remember once a while back this was also happening, but was fixed in a later release. 
Here is the full output if it is helpful.
```
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc001002000, 0x1b1174, 0x1b1174, 0xc001002000)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:182 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc0005989b0, 0x44, 0xc0005439d8)
        C:/Users/Afonso/GitHub/spicetify-cli/src/utils/utils.go:190 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc0005989b0, 0x44, 0xc00016a100, 0x9, 0x10, 0xc00009c0c0, 0x1, 0x2, 0x101)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:155 +0x9e
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc00000e580, 0x37, 0xc00016a100, 0x9, 0x10, 0xc00009c0c0, 0x1, 0x2, 0x101)
        C:/Users/Afonso/GitHub/spicetify-cli/src/apply/apply.go:34 +0x484
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x436634, 0x5)
        C:/Users/Afonso/GitHub/spicetify-cli/src/cmd/apply.go:73 +0x598
main.main()
        C:/Users/Afonso/GitHub/spicetify-cli/spicetify.go:192 +0x519
```

**Comment by TheGeeKing** [comment]
@jack-mil did you try to delete spicetify-cli folder and .spicetify folder and reinstall spicetify after? Should fix the issue

**Comment by nils-kt** [comment]
I had exactly the same problem. After I reinstalled Spotify and spicetify, it works now. I think the issue can be closed.

**Comment by TheGeeKing** [comment]
Any update @dfrazao? If it is fixed please close this issue.
