### ISSUE TITLE
Error starting WebNowPlaying extension

### ISSUE THREAD

**Issue by vancejc-mt** [khanhas/spicetify-cli#209]
I'd previously been using the SpotifyControl rainmeter widget (which uses the webnowplaying extension) without issue, this morning however it stopped working. Looking at the log I see the following:

```ERRO (09:51:33.952) : WebNowPlaying.dll - Error starting WebNowPlaying plugin
DBUG (09:51:33.953) : Error:System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at WebSocketSharp.Server.WebSocketServer.startReceiving()
   at WebSocketSharp.Server.WebSocketServer.Start()
   at WebNowPlaying.Measure..ctor(API api)
```

[Applied backup](https://github.com/khanhas/spicetify-cli/wiki/Guide-for-Rainmeter-user) as I'd done before, thinking spotify just updated, but didn't seem to fix anything.  Not sure why it would be failing to attach to the socket all the sudden.

Any idea?

**Comment by khanhas** [comment]
Why would this be Spicetify Issue?

**Comment by vancejc-mt** [comment]
Bah, sorry, didn't grab enough of the log:
```
NOTE (09:51:33.947) SpotifyControl\SpotifyControl.ini: Refreshing skin
DBUG (09:51:33.948) : Reading file: C:\Users\jeffv\AppData\Roaming\Rainmeter\Rainmeter.ini
DBUG (09:51:33.949) SpotifyControl\SpotifyControl.ini: Reading file: C:\Users\jeffv\Documents\Rainmeter\Skins\SpotifyControl\SpotifyControl.ini
ERRO (09:51:33.952) : WebNowPlaying.dll - Error starting WebNowPlaying plugin
DBUG (09:51:33.953) : Error:System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at WebSocketSharp.Server.WebSocketServer.startReceiving()
   at WebSocketSharp.Server.WebSocketServer.Start()
   at WebNowPlaying.Measure..ctor(API api)
```
Seems that it might have to do with the webnowplaying plugin?

**Comment by khanhas** [comment]
This is WebNowPlaying _plugin_ issue, not Spicetify WebNowPlaying _extension_ issue.
Anyway, did you notice any Windows Update? Especially security update that might block apps from accessing WebSocket?
