### ISSUE TITLE
Netease lyrics not working anymore - Karaoke

### ISSUE THREAD

**Issue by hennaceur** [khanhas/spicetify-cli#839]
## ℹ Computer information

- Spotify version: 1.1.62.583
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

Musixmatch works fine as long as I don't skip often which is annoying. But netease doesn't seem to be working for me even when prioritizing it and disabling Musixmatch.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/60199730/124621200-a615d580-de54-11eb-82db-ec2e1fe3c34f.png)

**Comment by hennaceur** [comment]
```console
vendor~xpui.js:29 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
7673 @ vendor~xpui.js:29
xpui.js:1 AllboardingAPINoOp.shouldShowOnLoad
spicetifyWrapper.js:821 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Spicetify._cloneSidebarItem @ spicetifyWrapper.js:821
xpui.js:1 No container found for fullscreen video!
(anonymous) @ xpui.js:1
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2364353)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2366635)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1799495
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:2647517)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2671369)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2873919)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2617025)
    at Cs (https://xpui.app.spotify.com/vendor~xpui.js:29:2671148)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2655919)
    at ys (https://xpui.app.spotify.com/vendor~xpui.js:29:2654841)
c @ vendor~xpui.js:29
4vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
4vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by saxobroko** [comment]
The website from the code "ProviderNetease.js" is having issues
https://music.xianqiao.wang/albums

**Comment by afonsojramos** [comment]
We need to investigate whether or not we still need this provider.
I believe it was the one used in Karaoke, so... that's why it is not working actually.

**Comment by mchyla7** [comment]
Am I lonely, or karaoke work on some songs?

https://user-images.githubusercontent.com/64330284/141688361-aec36d49-c680-44de-a900-7d4d4982c68b.mp4

**Comment by TheGeeKing** [comment]
> Am I lonely, or karaoke work on some songs?
> 
> https://user-images.githubusercontent.com/64330284/141688361-aec36d49-c680-44de-a900-7d4d4982c68b.mp4
> 
> 
> 

It seems a bit random or takes parameters that we don't know. Tried with your song and mine don't have karaoke for it.
