### ISSUE TITLE
Spicetify fails to apply additional modifications.

### ISSUE THREAD

**Issue by KarkaLT** [khanhas/spicetify-cli#877]
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Try to apply themes.

### ✔️ Expected result

Spicetify applies themes correctly

### ❌ Actual result

Spicetify fails to apply themes with error `Cannot find symbol for Custom app React symbols`

Full error:
```spicetify v2.5.0
Overwriting themed assets:
OK
Transferring user.css:
OK
Overwriting custom assets:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc0006aa000, 0x1aaa1f, 0x1aaa1f, 0xc0006aa000)
        D:/Code/spicetify-cli/src/apply/apply.go:180 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc000350c00, 0x38, 0xc0004339d8)
        D:/Code/spicetify-cli/src/utils/utils.go:190 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc000350c00, 0x38, 0xc0000aa580, 0x6, 0x8, 0xc0000204c0, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:155 +0x9e
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc00000e810, 0x2b, 0xc0000aa580, 0x6, 0x8, 0xc0000204c0, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:34 +0x484
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x11252d4, 0x5)
        D:/Code/spicetify-cli/src/cmd/apply.go:73 +0x598
main.main()
        D:/Code/spicetify-cli/spicetify.go:189 +0x519
```

**Comment by Rachniotov** [comment]
#845
